### ISSUE TITLE
Update the list of themes in README.md

### ISSUE THREAD

**Issue by smithandrewl** [w-w-wood-products-inc/mozaik-themes#1]
Readme.md contains a list of the themes in the project, but it is out of date.

To resolve this issue, make sure that the following themes are listed once in the README.md file.

Themes:
  1. Spice Bush
  2. Night Green
  3. Twilight
  4. Sunset
  5. Blue
  6. Charcoal
  7. Iceberg

**Comment by DeliciousCheese** [comment]
I can sort this out if you'd like
